ARG sourceimage=freqtradeorg/freqtrade
ARG sourcetag=develop_freqai
FROM ${sourceimage}:${sourcetag}

# 安装依赖
COPY requirements-freqai.txt requirements-freqai-rl.txt /freqtrade/

RUN pip install -r requirements-freqai-rl.txt --user --no-cache-dir