FROM freqtradeorg/freqtrade:develop

# 安装依赖
COPY requirements-dev.txt /freqtrade/

RUN pip install numpy --user --no-cache-dir \
  && pip install -r requirements-dev.txt --user --no-cache-dir

# 清空ENTRYPOINT以允许所有命令
ENTRYPOINT []